// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvZdBhRxsBCSST0Tsmcy_wXJ5BaJuDClg',
    appId: '1:992766496792:web:2e4ce7f7f35945a99c336d',
    messagingSenderId: '992766496792',
    projectId: 'taxi-test-37094',
    authDomain: 'taxi-test-37094.firebaseapp.com',
    databaseURL: 'https://taxi-test-37094-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-test-37094.appspot.com',
    measurementId: 'G-1KPS1HVLW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHwNDIujjzA8F_LdiKENGzfiH010IFdAA',
    appId: '1:992766496792:android:d251d1af230f8fe49c336d',
    messagingSenderId: '992766496792',
    projectId: 'taxi-test-37094',
    databaseURL: 'https://taxi-test-37094-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-test-37094.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABUcjb8K-FAjyhzuYuLGgrqRFD_6NO9vw',
    appId: '1:992766496792:ios:f335dab97527c4359c336d',
    messagingSenderId: '992766496792',
    projectId: 'taxi-test-37094',
    databaseURL: 'https://taxi-test-37094-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-test-37094.appspot.com',
    iosClientId: '992766496792-9ca2cvm9vu5l7n1goj8sj9b2b9fp3bm4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseRegist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABUcjb8K-FAjyhzuYuLGgrqRFD_6NO9vw',
    appId: '1:992766496792:ios:eb93cc05ff4453939c336d',
    messagingSenderId: '992766496792',
    projectId: 'taxi-test-37094',
    databaseURL: 'https://taxi-test-37094-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-test-37094.appspot.com',
    iosClientId: '992766496792-tavf4b5tumloq4qub6gsh99vbei8q0lg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseRegist.RunnerTests',
  );
}
